[project]
name = "mesh-temperature-data-flaskapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-bootstrap>=3.3.7.1",
    "flask-mqtt>=1.2.1",
]
